//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Internal/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""GameplayControls"",
            ""id"": ""549b8653-986f-4c98-90b9-701fa2a13662"",
            ""actions"": [
                {
                    ""name"": ""MoveLeft"",
                    ""type"": ""Button"",
                    ""id"": ""e913bf30-190a-455c-b589-d6aca3adf405"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveRight"",
                    ""type"": ""Button"",
                    ""id"": ""97bb8bdc-ddb6-4783-a392-9268f6ea6d54"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveUp"",
                    ""type"": ""Button"",
                    ""id"": ""6c927afd-3cc0-4d85-897c-b8e28309ce56"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveDown"",
                    ""type"": ""Button"",
                    ""id"": ""f9d502a4-cd81-4198-9ec3-595c52822744"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AxisXLeft"",
                    ""type"": ""Value"",
                    ""id"": ""f69eea21-a7ce-49a8-aeac-af937026baac"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""AxisYLeft"",
                    ""type"": ""Value"",
                    ""id"": ""4c46a19a-9251-44c7-bb31-e19ece2170ed"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""AxisXRight"",
                    ""type"": ""Value"",
                    ""id"": ""d581e084-04bf-4453-b60c-626c6ba1ac1d"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""AxisYRight"",
                    ""type"": ""Value"",
                    ""id"": ""5261f47f-69b3-448a-a849-37b52a912cba"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""660e1a1b-2eb7-4c1e-ac8f-73a8fd745c1a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""e81f2d43-37e2-4981-a7a8-a799368eb424"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""ef3ad862-69ac-4b10-a6dc-a67a3bc7155d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UILeft"",
                    ""type"": ""Button"",
                    ""id"": ""1dcbf704-887b-4fbb-a5b6-79187e61a6e1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UIRight"",
                    ""type"": ""Button"",
                    ""id"": ""30c3fd5c-6020-49e7-a862-b8f27efaed35"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UIUp"",
                    ""type"": ""Button"",
                    ""id"": ""b4b6db1d-a9d6-4964-ba54-61229e986c70"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UIDown"",
                    ""type"": ""Button"",
                    ""id"": ""f84afe1a-be92-4946-b63c-dd0fc774b107"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""36c3d218-4a1d-445e-908c-429aeea89db9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb517ae6-6e9a-4c71-9f80-b95844cefebc"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0b87b76-753f-4722-a3d4-e2674ddec17e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9549d70b-d639-42d0-a542-aeb8746d54ca"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d29c483-57a8-42d5-9939-709e0ebe1e59"",
                    ""path"": ""<Gamepad>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AxisXLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c38f746-3261-4179-b049-4d58521d8e61"",
                    ""path"": ""<Gamepad>/leftStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AxisYLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""974ac1cb-066c-41a9-9351-faab1cb2e651"",
                    ""path"": ""<Gamepad>/rightStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AxisXRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""677f6c70-bd87-4712-ad64-0fd39585ffa2"",
                    ""path"": ""<Gamepad>/rightStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AxisYRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62945c55-dfb2-43dc-8556-6ce2164b2a10"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""506e46f6-b91c-49d6-a813-c480f624b82d"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aa26a32f-b33e-4d18-b02e-09e0b5165594"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""745f4e88-d316-4758-88db-f28c60223609"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16376a0c-d9f5-44c0-915f-d6d012fe8bb9"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f312dfd-f924-490e-9f48-d19c9251b92e"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10f18627-7f5f-4ce3-b8bf-fa4580f7f200"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UILeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51654baf-f166-4915-b625-53e050e408b9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UILeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""217730bf-a159-4ca5-8a61-5e0e46451874"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UIRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3308a532-a674-4b9c-8027-80b210bab0c7"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UIUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d85b0c68-711d-4c88-9314-a5f129d4af98"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UIDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb265abd-7d74-47cc-9dd9-eb593eaf0235"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UIRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf1d6adf-14dc-4614-b5fb-60276ce995a2"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UIUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e11deaf8-08f1-4cea-be5b-b9269f34bea8"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UIDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GameplayControls
        m_GameplayControls = asset.FindActionMap("GameplayControls", throwIfNotFound: true);
        m_GameplayControls_MoveLeft = m_GameplayControls.FindAction("MoveLeft", throwIfNotFound: true);
        m_GameplayControls_MoveRight = m_GameplayControls.FindAction("MoveRight", throwIfNotFound: true);
        m_GameplayControls_MoveUp = m_GameplayControls.FindAction("MoveUp", throwIfNotFound: true);
        m_GameplayControls_MoveDown = m_GameplayControls.FindAction("MoveDown", throwIfNotFound: true);
        m_GameplayControls_AxisXLeft = m_GameplayControls.FindAction("AxisXLeft", throwIfNotFound: true);
        m_GameplayControls_AxisYLeft = m_GameplayControls.FindAction("AxisYLeft", throwIfNotFound: true);
        m_GameplayControls_AxisXRight = m_GameplayControls.FindAction("AxisXRight", throwIfNotFound: true);
        m_GameplayControls_AxisYRight = m_GameplayControls.FindAction("AxisYRight", throwIfNotFound: true);
        m_GameplayControls_Interact = m_GameplayControls.FindAction("Interact", throwIfNotFound: true);
        m_GameplayControls_Shoot = m_GameplayControls.FindAction("Shoot", throwIfNotFound: true);
        m_GameplayControls_Pause = m_GameplayControls.FindAction("Pause", throwIfNotFound: true);
        m_GameplayControls_UILeft = m_GameplayControls.FindAction("UILeft", throwIfNotFound: true);
        m_GameplayControls_UIRight = m_GameplayControls.FindAction("UIRight", throwIfNotFound: true);
        m_GameplayControls_UIUp = m_GameplayControls.FindAction("UIUp", throwIfNotFound: true);
        m_GameplayControls_UIDown = m_GameplayControls.FindAction("UIDown", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GameplayControls
    private readonly InputActionMap m_GameplayControls;
    private List<IGameplayControlsActions> m_GameplayControlsActionsCallbackInterfaces = new List<IGameplayControlsActions>();
    private readonly InputAction m_GameplayControls_MoveLeft;
    private readonly InputAction m_GameplayControls_MoveRight;
    private readonly InputAction m_GameplayControls_MoveUp;
    private readonly InputAction m_GameplayControls_MoveDown;
    private readonly InputAction m_GameplayControls_AxisXLeft;
    private readonly InputAction m_GameplayControls_AxisYLeft;
    private readonly InputAction m_GameplayControls_AxisXRight;
    private readonly InputAction m_GameplayControls_AxisYRight;
    private readonly InputAction m_GameplayControls_Interact;
    private readonly InputAction m_GameplayControls_Shoot;
    private readonly InputAction m_GameplayControls_Pause;
    private readonly InputAction m_GameplayControls_UILeft;
    private readonly InputAction m_GameplayControls_UIRight;
    private readonly InputAction m_GameplayControls_UIUp;
    private readonly InputAction m_GameplayControls_UIDown;
    public struct GameplayControlsActions
    {
        private @PlayerInput m_Wrapper;
        public GameplayControlsActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveLeft => m_Wrapper.m_GameplayControls_MoveLeft;
        public InputAction @MoveRight => m_Wrapper.m_GameplayControls_MoveRight;
        public InputAction @MoveUp => m_Wrapper.m_GameplayControls_MoveUp;
        public InputAction @MoveDown => m_Wrapper.m_GameplayControls_MoveDown;
        public InputAction @AxisXLeft => m_Wrapper.m_GameplayControls_AxisXLeft;
        public InputAction @AxisYLeft => m_Wrapper.m_GameplayControls_AxisYLeft;
        public InputAction @AxisXRight => m_Wrapper.m_GameplayControls_AxisXRight;
        public InputAction @AxisYRight => m_Wrapper.m_GameplayControls_AxisYRight;
        public InputAction @Interact => m_Wrapper.m_GameplayControls_Interact;
        public InputAction @Shoot => m_Wrapper.m_GameplayControls_Shoot;
        public InputAction @Pause => m_Wrapper.m_GameplayControls_Pause;
        public InputAction @UILeft => m_Wrapper.m_GameplayControls_UILeft;
        public InputAction @UIRight => m_Wrapper.m_GameplayControls_UIRight;
        public InputAction @UIUp => m_Wrapper.m_GameplayControls_UIUp;
        public InputAction @UIDown => m_Wrapper.m_GameplayControls_UIDown;
        public InputActionMap Get() { return m_Wrapper.m_GameplayControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayControlsActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayControlsActionsCallbackInterfaces.Add(instance);
            @MoveLeft.started += instance.OnMoveLeft;
            @MoveLeft.performed += instance.OnMoveLeft;
            @MoveLeft.canceled += instance.OnMoveLeft;
            @MoveRight.started += instance.OnMoveRight;
            @MoveRight.performed += instance.OnMoveRight;
            @MoveRight.canceled += instance.OnMoveRight;
            @MoveUp.started += instance.OnMoveUp;
            @MoveUp.performed += instance.OnMoveUp;
            @MoveUp.canceled += instance.OnMoveUp;
            @MoveDown.started += instance.OnMoveDown;
            @MoveDown.performed += instance.OnMoveDown;
            @MoveDown.canceled += instance.OnMoveDown;
            @AxisXLeft.started += instance.OnAxisXLeft;
            @AxisXLeft.performed += instance.OnAxisXLeft;
            @AxisXLeft.canceled += instance.OnAxisXLeft;
            @AxisYLeft.started += instance.OnAxisYLeft;
            @AxisYLeft.performed += instance.OnAxisYLeft;
            @AxisYLeft.canceled += instance.OnAxisYLeft;
            @AxisXRight.started += instance.OnAxisXRight;
            @AxisXRight.performed += instance.OnAxisXRight;
            @AxisXRight.canceled += instance.OnAxisXRight;
            @AxisYRight.started += instance.OnAxisYRight;
            @AxisYRight.performed += instance.OnAxisYRight;
            @AxisYRight.canceled += instance.OnAxisYRight;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Shoot.started += instance.OnShoot;
            @Shoot.performed += instance.OnShoot;
            @Shoot.canceled += instance.OnShoot;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @UILeft.started += instance.OnUILeft;
            @UILeft.performed += instance.OnUILeft;
            @UILeft.canceled += instance.OnUILeft;
            @UIRight.started += instance.OnUIRight;
            @UIRight.performed += instance.OnUIRight;
            @UIRight.canceled += instance.OnUIRight;
            @UIUp.started += instance.OnUIUp;
            @UIUp.performed += instance.OnUIUp;
            @UIUp.canceled += instance.OnUIUp;
            @UIDown.started += instance.OnUIDown;
            @UIDown.performed += instance.OnUIDown;
            @UIDown.canceled += instance.OnUIDown;
        }

        private void UnregisterCallbacks(IGameplayControlsActions instance)
        {
            @MoveLeft.started -= instance.OnMoveLeft;
            @MoveLeft.performed -= instance.OnMoveLeft;
            @MoveLeft.canceled -= instance.OnMoveLeft;
            @MoveRight.started -= instance.OnMoveRight;
            @MoveRight.performed -= instance.OnMoveRight;
            @MoveRight.canceled -= instance.OnMoveRight;
            @MoveUp.started -= instance.OnMoveUp;
            @MoveUp.performed -= instance.OnMoveUp;
            @MoveUp.canceled -= instance.OnMoveUp;
            @MoveDown.started -= instance.OnMoveDown;
            @MoveDown.performed -= instance.OnMoveDown;
            @MoveDown.canceled -= instance.OnMoveDown;
            @AxisXLeft.started -= instance.OnAxisXLeft;
            @AxisXLeft.performed -= instance.OnAxisXLeft;
            @AxisXLeft.canceled -= instance.OnAxisXLeft;
            @AxisYLeft.started -= instance.OnAxisYLeft;
            @AxisYLeft.performed -= instance.OnAxisYLeft;
            @AxisYLeft.canceled -= instance.OnAxisYLeft;
            @AxisXRight.started -= instance.OnAxisXRight;
            @AxisXRight.performed -= instance.OnAxisXRight;
            @AxisXRight.canceled -= instance.OnAxisXRight;
            @AxisYRight.started -= instance.OnAxisYRight;
            @AxisYRight.performed -= instance.OnAxisYRight;
            @AxisYRight.canceled -= instance.OnAxisYRight;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Shoot.started -= instance.OnShoot;
            @Shoot.performed -= instance.OnShoot;
            @Shoot.canceled -= instance.OnShoot;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @UILeft.started -= instance.OnUILeft;
            @UILeft.performed -= instance.OnUILeft;
            @UILeft.canceled -= instance.OnUILeft;
            @UIRight.started -= instance.OnUIRight;
            @UIRight.performed -= instance.OnUIRight;
            @UIRight.canceled -= instance.OnUIRight;
            @UIUp.started -= instance.OnUIUp;
            @UIUp.performed -= instance.OnUIUp;
            @UIUp.canceled -= instance.OnUIUp;
            @UIDown.started -= instance.OnUIDown;
            @UIDown.performed -= instance.OnUIDown;
            @UIDown.canceled -= instance.OnUIDown;
        }

        public void RemoveCallbacks(IGameplayControlsActions instance)
        {
            if (m_Wrapper.m_GameplayControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayControlsActions @GameplayControls => new GameplayControlsActions(this);
    public interface IGameplayControlsActions
    {
        void OnMoveLeft(InputAction.CallbackContext context);
        void OnMoveRight(InputAction.CallbackContext context);
        void OnMoveUp(InputAction.CallbackContext context);
        void OnMoveDown(InputAction.CallbackContext context);
        void OnAxisXLeft(InputAction.CallbackContext context);
        void OnAxisYLeft(InputAction.CallbackContext context);
        void OnAxisXRight(InputAction.CallbackContext context);
        void OnAxisYRight(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnUILeft(InputAction.CallbackContext context);
        void OnUIRight(InputAction.CallbackContext context);
        void OnUIUp(InputAction.CallbackContext context);
        void OnUIDown(InputAction.CallbackContext context);
    }
}
